### Fish Market

This dataset is a record of 7 common different fish species in fish market sales. With this dataset, a predictive model can be performed using machine friendly data and estimate the weight of fish can be predicted.

### Problem

This problem is solved using classification to identify the kind of species taking the given factors as features.

Import all the needed libraries


In [147]:
# to perform linear algebra
import numpy as np

# data processing
import pandas as pd

# visualization
import matplotlib.pyplot as plt


Read the Data


In [148]:
data = pd.read_csv("Fish.csv")

data.head()


Species  Weight  Length1  Length2  Length3   Height   Width
0   Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1   Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2   Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3   Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4   Bream   430.0     26.5     29.0     34.0  12.4440  5.1340

Get the Data

In [149]:
Y = data.Species.values
x = data.drop(['Species'], axis=1)[:].values
print(Y)
x


['Bream' 'Bream' 'Bream' 'Bream' 'Bream' 'Bream' 'Bream' 'Bream' 'Bream'
 'Bream' 'Bream' 'Bream' 'Bream' 'Bream' 'Bream' 'Bream' 'Bream' 'Bream'
 'Bream' 'Bream' 'Bream' 'Bream' 'Bream' 'Bream' 'Bream' 'Bream' 'Bream'
 'Bream' 'Bream' 'Bream' 'Bream' 'Bream' 'Bream' 'Bream' 'Bream' 'Roach'
 'Roach' 'Roach' 'Roach' 'Roach' 'Roach' 'Roach' 'Roach' 'Roach' 'Roach'
 'Roach' 'Roach' 'Roach' 'Roach' 'Roach' 'Roach' 'Roach' 'Roach' 'Roach'
 'Roach' 'Whitefish' 'Whitefish' 'Whitefish' 'Whitefish' 'Whitefish'
 'Whitefish' 'Parkki' 'Parkki' 'Parkki' 'Parkki' 'Parkki' 'Parkki'
 'Parkki' 'Parkki' 'Parkki' 'Parkki' 'Parkki' 'Perch' 'Perch' 'Perch'
 'Perch' 'Perch' 'Perch' 'Perch' 'Perch' 'Perch' 'Perch' 'Perch' 'Perch'
 'Perch' 'Perch' 'Perch' 'Perch' 'Perch' 'Perch' 'Perch' 'Perch' 'Perch'
 'Perch' 'Perch' 'Perch' 'Perch' 'Perch' 'Perch' 'Perch' 'Perch' 'Perch'
 'Perch' 'Perch' 'Perch' 'Perch' 'Perch' 'Perch' 'Perch' 'Perch' 'Perch'
 'Perch' 'Perch' 'Perch' 'Perch' 'Perch' 'Perch' 'Perch' 'Perch'

array([[2.42000e+02, 2.32000e+01, 2.54000e+01, 3.00000e+01, 1.15200e+01,
        4.02000e+00],
       [2.90000e+02, 2.40000e+01, 2.63000e+01, 3.12000e+01, 1.24800e+01,
        4.30560e+00],
       [3.40000e+02, 2.39000e+01, 2.65000e+01, 3.11000e+01, 1.23778e+01,
        4.69610e+00],
       [3.63000e+02, 2.63000e+01, 2.90000e+01, 3.35000e+01, 1.27300e+01,
        4.45550e+00],
       [4.30000e+02, 2.65000e+01, 2.90000e+01, 3.40000e+01, 1.24440e+01,
        5.13400e+00],
       [4.50000e+02, 2.68000e+01, 2.97000e+01, 3.47000e+01, 1.36024e+01,
        4.92740e+00],
       [5.00000e+02, 2.68000e+01, 2.97000e+01, 3.45000e+01, 1.41795e+01,
        5.27850e+00],
       [3.90000e+02, 2.76000e+01, 3.00000e+01, 3.50000e+01, 1.26700e+01,
        4.69000e+00],
       [4.50000e+02, 2.76000e+01, 3.00000e+01, 3.51000e+01, 1.40049e+01,
        4.84380e+00],
       [5.00000e+02, 2.85000e+01, 3.07000e+01, 3.62000e+01, 1.42266e+01,
        4.95940e+00],
       [4.75000e+02, 2.84000e+01, 3.10000e+01, 3.6

Label Encode

In [150]:
from sklearn.preprocessing import LabelEncoder

Encoder = LabelEncoder()
Y = Encoder.fit_transform(Y)
Y_classes = Encoder.classes_
print(Y_classes)
Y


['Bream' 'Parkki' 'Perch' 'Pike' 'Roach' 'Smelt' 'Whitefish']


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 6, 6, 6, 6, 6, 6, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5])

Split into train and test data set

In [151]:
from sklearn.model_selection import train_test_split

# Split the training the and test dataset into 50-50 (generally the distribution is 70-30, but 50-50 gives us the best results here)
x_train, x_test, y_train, y_test = train_test_split(
    x,
    Y,
    test_size=0.3,
    random_state=42,
)


# Display the current shape
print("x train: ", x_train.shape)
print("x test: ", x_test.shape)
print("y train: ", y_train.shape)
print("y test: ", y_test.shape)

x_train


x train:  (111, 6)
x test:  (48, 6)
y train:  (111,)
y test:  (48,)


array([[1.30000e+02, 1.93000e+01, 2.13000e+01, 2.28000e+01, 6.38400e+00,
        3.53400e+00],
       [8.50000e+01, 1.82000e+01, 2.00000e+01, 2.10000e+01, 5.08200e+00,
        2.77200e+00],
       [6.85000e+02, 3.40000e+01, 3.65000e+01, 3.90000e+01, 1.08810e+01,
        6.86400e+00],
       [5.00000e+02, 2.87000e+01, 3.10000e+01, 3.62000e+01, 1.43714e+01,
        4.81460e+00],
       [5.14000e+02, 3.05000e+01, 3.28000e+01, 3.40000e+01, 1.00300e+01,
        6.01800e+00],
       [2.00000e+02, 2.12000e+01, 2.30000e+01, 2.58000e+01, 1.03458e+01,
        3.66360e+00],
       [1.00000e+03, 4.11000e+01, 4.40000e+01, 4.66000e+01, 1.24888e+01,
        7.59580e+00],
       [7.14000e+02, 3.27000e+01, 3.60000e+01, 4.15000e+01, 1.65170e+01,
        5.85150e+00],
       [8.70000e+00, 1.08000e+01, 1.13000e+01, 1.26000e+01, 1.97820e+00,
        1.28520e+00],
       [1.00000e+03, 3.98000e+01, 4.30000e+01, 4.52000e+01, 1.19328e+01,
        7.27720e+00],
       [1.10000e+02, 1.91000e+01, 2.08000e+01, 2.3

Train and score the model

In [152]:
from sklearn import svm

model = svm.SVC(C=1.0, kernel='linear', degree=3, gamma='auto').fit(x_train, y_train)
model.score(x_test, y_test)

0.9583333333333334

Predict values

In [156]:
def predict(_model, col):
    col = col.reshape(1, -1)
    prediction = _model.predict(col)
    return Y_classes[prediction][0]


for i in range(len(x_test)):
    prediction = str(predict(model, x_test[i]))
    actual = str(Y_classes[y_test[i]])
    print("Returned value: " + prediction + ". Actual value: " + actual +
          ". Prediction is " + str(prediction == actual))


Returned value: Perch. Actual value: Perch. Prediction is True
Returned value: Smelt. Actual value: Smelt. Prediction is True
Returned value: Pike. Actual value: Pike. Prediction is True
Returned value: Roach. Actual value: Whitefish. Prediction is False
Returned value: Perch. Actual value: Perch. Prediction is True
Returned value: Bream. Actual value: Bream. Prediction is True
Returned value: Smelt. Actual value: Smelt. Prediction is True
Returned value: Roach. Actual value: Roach. Prediction is True
Returned value: Perch. Actual value: Perch. Prediction is True
Returned value: Pike. Actual value: Pike. Prediction is True
Returned value: Bream. Actual value: Bream. Prediction is True
Returned value: Whitefish. Actual value: Whitefish. Prediction is True
Returned value: Bream. Actual value: Bream. Prediction is True
Returned value: Parkki. Actual value: Parkki. Prediction is True
Returned value: Bream. Actual value: Bream. Prediction is True
Returned value: Bream. Actual value: Bream. 

Save the model

In [157]:
from joblib import dump, load
dump(model, "fish_classification_model.joblib")
model_2 = load("fish_classification_model.joblib")


for i in range(len(x_test)):
    prediction = str(predict(model, x_test[i]))
    actual = str(Y_classes[y_test[i]])
    print("Returned value: " + prediction + ". Actual value: " + actual +
          ". Prediction is " + str(prediction == actual))


Returned value: Perch. Actual value: Perch. Prediction is True
Returned value: Smelt. Actual value: Smelt. Prediction is True
Returned value: Pike. Actual value: Pike. Prediction is True
Returned value: Roach. Actual value: Whitefish. Prediction is False
Returned value: Perch. Actual value: Perch. Prediction is True
Returned value: Bream. Actual value: Bream. Prediction is True
Returned value: Smelt. Actual value: Smelt. Prediction is True
Returned value: Roach. Actual value: Roach. Prediction is True
Returned value: Perch. Actual value: Perch. Prediction is True
Returned value: Pike. Actual value: Pike. Prediction is True
Returned value: Bream. Actual value: Bream. Prediction is True
Returned value: Whitefish. Actual value: Whitefish. Prediction is True
Returned value: Bream. Actual value: Bream. Prediction is True
Returned value: Parkki. Actual value: Parkki. Prediction is True
Returned value: Bream. Actual value: Bream. Prediction is True
Returned value: Bream. Actual value: Bream. 

Predict values